---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: factoriotools/factorio:0.18.34
        name: Factorio
        ports:
        - containerPort: 27015
          protocol: TCP
        -containerPort: 34197
          protocol: UDP
